CREATE DATABASE IF NOT EXISTS GAMR;
USE GAMR;
CREATE TABLE IF NOT EXISTS users 
(
	UID int NOT NULL AUTO_INCREMENT,
	username VARCHAR(80) NOT NULL UNIQUE,
	password VARCHAR(255) NOT NULL,
	email VARCHAR(255) UNIQUE,
	firstname VARCHAR(255),
	lastname VARCHAR(255),
	about VARCHAR(2000),
	PRIMARY KEY (UID)
);
CREATE TABLE IF NOT EXISTS sessions
(
	session int NOT NULL AUTO_INCREMENT,
	UID int NOT NULL,
	PRIMARY KEY (session)
);