CREATE DATABASE IF NOT EXISTS GAMR;
USE GAMR;
CREATE TABLE users 
(
	ID int NOT NULL AUTO_INCREMENT,
	username VARCHAR(1000) NOT NULL UNIQUE,
	password VARCHAR(255) NOT NULL,
	email VARCHAR(1000),
	firstname VARCHAR(255),
	lastname VARCHAR(255),
	about VARCHAR(2000)
	PRIMARY KEY (ID)
)